In [103]:
from sys import displayhook

import pandas as pd

# Wednesday-workingHours-stage1_flows
# firewall_test_20250731_160700-stage1_flows
df = pd.read_csv("dataset/Wednesday-workingHours-stage1_flows.csv")
df = df[(df['flow_id'] != 0) & (df['flow_start_timestamp_us'] != 0) &
        df['flow_id'].notna() & df['flow_start_timestamp_us'].notna()]
# 转换时间戳
df["datetime"] = pd.to_datetime(
    df["flow_start_timestamp_us"],
    unit="us"
)

In [104]:
flow_start_time = df["datetime"].min()
flow_end_time = df["datetime"].max()

print("Flow Start:", flow_start_time)
print("Flow End:", flow_end_time)

Flow Start: 2017-07-05 11:42:42.084372
Flow End: 2017-07-05 20:10:14.557249

In [105]:
# 只保留恶意流
malicious = df[df["label"] == 1]
display(malicious.shape)

(210183, 78)

In [106]:
start_time = malicious["datetime"].min()
end_time = malicious["datetime"].max()

print("Malicious Start:", start_time)
print("Malicious End:", end_time)

Malicious Start: 2017-07-05 11:42:42.234259
Malicious End: 2017-07-05 20:10:14.557249

In [107]:
malicious["second"] = malicious["datetime"].dt.floor("s")

result = (
    malicious
    .groupby("second")
    .size()
    .reset_index(name="malicious_flows")
)
display(result)

                  second  malicious_flows
0    2017-07-05 11:42:42                2
1    2017-07-05 11:42:43                1
2    2017-07-05 11:42:44                1
3    2017-07-05 11:42:48                7
4    2017-07-05 11:42:49                3
...                  ...              ...
8929 2017-07-05 20:07:37                7
8930 2017-07-05 20:07:49                1
8931 2017-07-05 20:10:09                2
8932 2017-07-05 20:10:10                1
8933 2017-07-05 20:10:14                1

[8934 rows x 2 columns]

In [108]:
df["second"] = df["datetime"].dt.floor("s")

result = (
    df.groupby(["second","label"])
      .size()
      .unstack(fill_value=0)
)

result.columns = ["benign","malicious"]
display(result)

                     benign  malicious
second
2017-07-05 11:42:42      21          2
2017-07-05 11:42:43      13          1
2017-07-05 11:42:44       2          1
2017-07-05 11:42:45       1          0
2017-07-05 11:42:46       1          0
...                     ...        ...
2017-07-05 20:08:52       1          0
2017-07-05 20:09:52       1          0
2017-07-05 20:10:09       0          2
2017-07-05 20:10:10       0          1
2017-07-05 20:10:14       0          1

[17825 rows x 2 columns]

In [109]:
malicious["minute"] = malicious["datetime"].dt.floor("min")

result = (
    malicious
    .groupby("minute")
    .size()
    .reset_index(name="malicious_flows")
)

display(result)

                 minute  malicious_flows
0   2017-07-05 11:42:00               15
1   2017-07-05 11:43:00               17
2   2017-07-05 11:44:00               47
3   2017-07-05 11:45:00               21
4   2017-07-05 11:46:00               52
..                  ...              ...
499 2017-07-05 20:04:00                3
500 2017-07-05 20:05:00                7
501 2017-07-05 20:06:00               19
502 2017-07-05 20:07:00               15
503 2017-07-05 20:10:00                4

[504 rows x 2 columns]

In [110]:
df["minute"] = df["datetime"].dt.floor("min")

result = (
    df.groupby("minute")["label"]
      .agg(
          total_flows="count",
          malicious_flows="sum"
      )
)

result["malicious_ratio"] = (
    result["malicious_flows"]
    / result["total_flows"]
)
display(result)

                     total_flows  malicious_flows  malicious_ratio
minute
2017-07-05 11:42:00          163               15         0.092025
2017-07-05 11:43:00          250               17         0.068000
2017-07-05 11:44:00          241               47         0.195021
2017-07-05 11:45:00          150               21         0.140000
2017-07-05 11:46:00          283               52         0.183746
...                          ...              ...              ...
2017-07-05 20:06:00          128               19         0.148438
2017-07-05 20:07:00          158               15         0.094937
2017-07-05 20:08:00           22                0         0.000000
2017-07-05 20:09:00            1                0         0.000000
2017-07-05 20:10:00            4                4         1.000000

[509 rows x 3 columns]

In [111]:
malicious = df[df["label"] == 1].copy()

malicious = malicious.sort_values(
    "flow_start_timestamp_us"
)

malicious["delta_t"] = (
    malicious["flow_start_timestamp_us"]
      .diff()
)
display(malicious[["flow_id","delta_t"]])

                 flow_id      delta_t
11       724663271725813          NaN
10       800207587720919     214197.0
129      884191366591415    1543842.0
8       1309374600528395     705780.0
113      197451637894494    3872182.0
...                  ...          ...
471214  1496170350971524   12396774.0
475003   345219650143157  140190775.0
473583   345259564686749         10.0
475157   670544048738377     682520.0
472281  1830420271129583    3942374.0

[210183 rows x 2 columns]

In [114]:
from sys import displayhook

import pandas as pd

# Wednesday-workingHours-stage1_flows
# firewall_test_20250731_160700-stage1_flows
df = pd.read_csv("dataset/ar002_et12_20260511_002-stage1_packets.csv")
print("0000",df.shape)

df = df[(df['flow_id'] != 0) & df['flow_id'].notna()]
print("11111",df.shape)

# df = df[(df['flow_start_timestamp_us'] != 0) & df['flow_start_timestamp_us'].notna()]
# print("22222",df.shape)

df = df[(df['flow_id'] != 0) & (df['timestamp_us'] != 0) &
        df['flow_id'].notna() & df['timestamp_us'].notna()]
print("22222",df.shape)

0000 (4690999, 40)
11111 (4668711, 40)
33333 (4668711, 40)